"use client"
import './globals.css'
import Link from "next/link"


export const metadata = {
  title: 'Assignment 5',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <section className={navigation}>
            <Link href="/">Home</Link>
            <Link href="/largeflasks">Large flask</Link>
            <Link href="/smallflasks">Small flask</Link>
            <Link href="/cans">Can</Link>
          </section>
        </header>

        <div>{children}</div>

      </body>
    </html>
  )
}
